### ISSUE TITLE
global config settings in legacy-config don't work?

### ISSUE THREAD

**Issue by Mariusthvdb** [rodrigofragadf/lovelace-cards#1]
HI,
thanks for your card! this has been a crucial condition for me to go to Lovelace...
So, now Ive implemented it I run into the following issues, I hope you can solve for me.

Have these legacy-configs directly copied from my regular Tiles card:

```
      - type: custom:tiles-card
        legacy_config:
          columns: 4
          row_height: 70px
          text_color_on: '#555b65'
          text_color_off: '#f0c209'
          color_on: '#f0c209'
          color_off: '#555b65'
#          text_uppercase: false
          text_size: 1em
#          text_sec_size: 1em
#          text_align: center
```

unfortunately this is displayed in the frontend, ignoring the colors for text and icon (icon was set in Tiles using the text color.

![schermafbeelding 2018-12-02 om 12 42 38](https://user-images.githubusercontent.com/33354141/49339275-c7284100-f62f-11e8-9d45-f6d766737095.jpg)

while the original Tiles card 

```
    input_text.tiles_switches:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 4
        row_height: 70px
        color_on: '#F0C209'
        color_off: '#555B65'
        text_uppercase: false
        text_color_on: '#555B65'
        text_color_off: '#F0C209'
        text_size: 1em
        text_sec_size: 1em
        text_align: center
```

displays like this:

![schermafbeelding 2018-12-02 om 12 43 19](https://user-images.githubusercontent.com/33354141/49339292-e0c98880-f62f-11e8-951c-97daaa4e20b1.jpg)

could you please have a look on how to change this?
I did try to use coloring per button, and believe that worked better, but I hope that a global color scheme could be set in the config section?

Ive tried almost all mentioned options in the tiles-card.js, but they simply dont stick.
Thanks for having a look!
